---
platform: linux
inputs:
- name: git-repo
outputs:
- name: stage-git-repo
- name: distribution-repository
caches:
- path: maven
- path: gradle
params:
  RELEASE_TYPE:
run:
  path: git-repo/ci/scripts/stage.sh
