resource_types:
- name: artifactory-resource
  type: registry-image
  source:
    repository: springio/artifactory-resource
    tag: 0.0.8
- name: pull-request
  type: registry-image
  source:
    repository: jtarchie/pr
resources:
- name: git-repo
  type: git
  icon: github
  source:
    uri: ((github-repo))
    username: ((github-username))
    password: ((github-password))
    branch: ((branch))
    ignore_paths: ["ci/images/*"]
- name: git-pull-request
  type: pull-request
  icon: source-pull
  source:
    access_token: ((github-ci-pull-request-token))
    repo: ((github-repo-name))
    base: ((branch))
    ignore_paths: ["ci/*"]
- name: ci-images-git-repo
  type: git
  icon: github-circle
  source:
    uri: ((github-repo))
    branch: ((branch))
    paths: ["ci/images/*"]
- name: ci-image
  type: registry-image
  icon: docker
  source:
    repository: ((docker-hub-organization))/ci-image
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: ((branch))
- name: artifactory-repo
  type: artifactory-resource
  icon: package-variant
  source:
    uri: ((artifactory-server))
    username: ((artifactory-username))
    password: ((artifactory-password))
    build_name: ((build-name))
- name: github-release
  type: github-release
  icon: briefcase-download
  source:
    owner: spring-io
    repository: spring-javaformat
    access_token: ((github-ci-release-token))
jobs:
- name: build-ci-images
  plan:
  - get: ci-images-git-repo
    trigger: true
  - put: ci-image
    params:
      build: ci-images-git-repo/ci/images
      dockerfile: ci-images-git-repo/ci/images/ci-image/Dockerfile
- name: build
  serial: true
  public: true
  plan:
  - get: ci-image
  - get: git-repo
    trigger: true
  - do:
    - task: build-project
      privileged: true
      timeout: 1h30m
      image: ci-image
      file: git-repo/ci/tasks/build-project.yml
  - put: artifactory-repo
    params: &artifactory-params
      repo: libs-snapshot-local
      build_number: "${BUILD_ID}"
      folder: distribution-repository
      build_uri: "https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
      build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
      disable_checksum_uploads: true
- name: build-pull-requests
  serial: true
  public: true
  plan:
  - get: ci-image
  - get: git-repo
    resource: git-pull-request
    trigger: true
    version: every
  - do:
    - put: git-pull-request
      params:
        path: git-repo
        status: pending
    - task: build-project
      timeout: 1h30m
      image: ci-image
      file: git-repo/ci/tasks/build-pr-project.yml
    on_success:
      put: git-pull-request
      params:
        path: git-repo
        status: success
    on_failure:
      put: git-pull-request
      params:
        path: git-repo
        status: failure
- name: stage-release
  serial: true
  plan:
  - get: ci-image
  - get: git-repo
    trigger: false
  - task: stage
    image: ci-image
    file: git-repo/ci/tasks/stage.yml
    params:
      RELEASE_TYPE: RELEASE
  - put: artifactory-repo
    params:
      <<: *artifactory-params
      repo: libs-staging-local
  - put: git-repo
    params:
      repository: stage-git-repo
- name: promote-release
  serial: true
  plan:
  - get: ci-image
  - get: git-repo
    trigger: false
  - get: artifactory-repo
    trigger: false
    passed: [stage-release]
    params:
      save_build_info: true
  - task: promote
    image: ci-image
    file: git-repo/ci/tasks/promote.yml
    params:
      RELEASE_TYPE: RELEASE
      ARTIFACTORY_SERVER: ((artifactory-server))
      ARTIFACTORY_USERNAME: ((artifactory-username))
      ARTIFACTORY_PASSWORD: ((artifactory-password))
      BINTRAY_USERNAME: ((bintray-username))
      BINTRAY_API_KEY: ((bintray-api-key))
      BINTRAY_SUBJECT: ((bintray-subject))
      BINTRAY_REPO: ((bintray-repo))
- name: sync-to-maven-central
  serial: true
  plan:
  - get: ci-image
  - get: git-repo
    trigger: false
  - get: artifactory-repo
    trigger: false
    passed: [promote-release]
    params:
      save_build_info: true
  - task: sync-to-maven-central
    image: ci-image
    file: git-repo/ci/tasks/sync-to-maven-central.yml
    params:
      BINTRAY_USERNAME: ((bintray-username))
      BINTRAY_API_KEY: ((bintray-api-key))
      BINTRAY_SUBJECT: ((bintray-subject))
      BINTRAY_REPO: ((bintray-repo))
      SONATYPE_USER_TOKEN: ((sonatype-user-token))
      SONATYPE_PASSWORD_TOKEN: ((sonatype-user-token-password))
  - task: generate-release-notes
    file: git-repo/ci/tasks/generate-release-notes.yml
    params:
      GITHUB_USERNAME: ((github-username))
      GITHUB_TOKEN: ((github-ci-release-token))
  - put: github-release
    params:
      name: generated-release-notes/tag
      tag: generated-release-notes/tag
      body: generated-release-notes/release-notes.md
- name: publish-eclipse-update-site
  serial: true
  plan:
  - get: ci-image
  - get: git-repo
    trigger: false
  - get: artifactory-repo
    trigger: false
    passed: [sync-to-maven-central]
    params:
      save_build_info: true
  - task: publish-eclipse-update-site
    image: ci-image
    file: git-repo/ci/tasks/publish-eclipse-update-site.yml
    params:
      BINTRAY_USERNAME: ((bintray-username))
      BINTRAY_API_KEY: ((bintray-api-key))
groups:
- name: "builds"
  jobs: ["build"]
- name: "releases"
  jobs: ["stage-release", "promote-release", "sync-to-maven-central", "publish-eclipse-update-site"]
- name: "ci-images"
  jobs: ["build-ci-images"]
- name: "pull-requests"
  jobs: ["build-pull-requests"]
